### ISSUE TITLE
Missing Content-Type v3.04.01

### ISSUE THREAD

**Issue by clandmeter** [fbb-git/gpg-remailer#2]
commit https://github.com/fbb-git/gpg-remailer/commit/ef2235d02adc56acfe03e6040ed43c033b466273 seems to break messages because of missing Content-Type Header.

In the log I don't see the -a (content-type) option applied to mail program anymore.

Switching to 3.04.00 makes it work again.

**Comment by fbb-git** [comment]
Dear Carlo Landmeter, you wrote:
> commit https://github.com/fbb-git/gpg-remailer/commit/ef2235d02adc56acfe03e6040ed43c033b466273 seems to break messages because of missing Content-Type Header.
> 
> In the log I don't see the -a (content-type) option applied to mail program anymore.
> 
> Switching to 3.04.00 makes it work again.

Commit ef2235 isn't a tagged commit, and shouldn't be used. The next tagged
commit is 3.04.01, referring to commit
1ec76411b556f065793981d5b217f5c2c9fa1af3. That commit is dated Oct. 5, and
logs of the gpg-remailer as I use it do show content-type entries. If you
experience changed gpg-logs, could you show entries that you do observe now, and
indicate what you miss, as compared to logs obtained with, e.g., 3.04.00?

Thx!

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by clandmeter** [comment]
Im not sure what you mean?

You latest tag(release) has commit ef2235d included (also mentioned in the [changelog](https://github.com/fbb-git/gpg-remailer/blob/master/gpg-remailer/changelog)) which is the only change related to "Content-Type". And this is exactly the option that is missing when gpg-remailer is executing /usr/bin/mail.

```Oct 30 16:00:28 /usr/bin/mail -s 'Subject: hello' -a "Reply-To: scurity@alpinelinux.org"  -a "X-GPG-remailer-from:  clandmeter@alpinelinux.org  Mon Oct 30 16:00:28 2017" -a "X-GPG-remailer-From:  Carlo Landmeter <clandmeter@alpinelinux.org>" -a "MIME-Version: 1.0" clandmeter@alpinelinux.org```

vs

```Oct 30 16:23:18 /usr/bin/mail -s 'Subject: hello' -a "Reply-To: scurity@alpinelinux.org"  -a "X-GPG-remailer-from:  clandmeter@alpinelinux.org  Mon Oct 30 16:23:18 2017" -a "X-GPG-remailer-From:  Carlo Landmeter <clandmeter@alpinelinux.org>" -a "MIME-Version: 1.0" -a "Content-Type: multipart/mixed; boundary=\"001a114483265d77dc055cc60e36\"" clandmeter@alpinelinux.org```

**Comment by fbb-git** [comment]
Dear Carlo Landmeter, you wrote:
> Im not sure what you mean?
> 
> You latest tag(release) has commit ef2235d included (also mentioned in the
[changelog](https://github.com/fbb-git/gpg-remailer/blob/master/gpg-remailer/changelog))
which is the only change related to "Content-Type". And this is exactly the
option that is missing when gpg-remailer is executing /usr/bin/mail.

Peculiar. Thanks for bringing this to my attention. I intend to fix it in the
next release, asap.

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by fbb-git** [comment]
Dear Carlo Landmeter, you wrote:

> You latest tag(release) has commit ef2235d included (also mentioned in the
> [changelog](https://github.com/fbb-git/gpg-remailer/blob/master/gpg-remailer/changelog)) 
> which is the only change related to "Content-Type". And this is exactly the
> option that is missing when gpg-remailer is executing /usr/bin/mail. 


I think I need some more information: when I run the latest gpg-remailer,
irrespective of the debug level, the content-type is reported in my logs. E.g.,

Oct 31 19:33:08 /usr/bin/mail -s 'Subject: Re: Subject: signed and encrypted'
-a "Reply-To: Frank <frank@localhost>"  -a "X-GPG-remailer-from:
f.b.brokken@rug.nl Thu May 11 19:17:50 2017" -a "X-GPG-remailer-From:  \"Frank
B. Brokken\" <f.b.brokken@rug.nl>" -a "MIME-Version: 1.0" -a "Content-Length:
3809" -a 'Content-Type: multipart/encrypted;
protocol="application/pgp-encrypted"; boundary="fKSV8VSAXo8yvqCT"' frank
Oct 31 19:33:08 GPG encrypted mail (Subject: Re: Subject: signed and
encrypted) sent to frank

Maybe you can send me the contents of your gpg-remailer.rc file and the e-mail
as received by the remailer?

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by clandmeter** [comment]
I've seen you an email with some additional information.

**Comment by fbb-git** [comment]
AFAICS the issue has been solved in version 3.04.02. Thanks for sending me the additional info.
